### ISSUE TITLE
Crash on host when swiping to remove playlist entry on guest

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#178]
To reproduce:
1. Establish a network with one guest.
2. From the guest, add 2 songs to the playlist and press play.
3. From the guest, swipe to remove the 2nd playlist entry.
4. From the guest, add a different song to the playlist.  This will become a new 2nd playlist entry.
5. From the guest, swipe to remove the new 2nd playlist entry.

The app on the host will force close.

Exception trace:
E/AndroidRuntime(19935): FATAL EXCEPTION: main
E/AndroidRuntime(19935): java.lang.NullPointerException
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.util.SongMetadataUtils.isTheSameEntry(SongMetadataUtils.java:57)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService.isCurrentEntry(PlaylistService.java:413)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService.access$400(PlaylistService.java:56)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.service.PlaylistService$6.onReceiveAction(PlaylistService.java:310)
E/AndroidRuntime(19935):    at com.lastcrusade.soundstream.util.BroadcastRegistrar$1.onReceive(BroadcastRegistrar.java:83)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
E/AndroidRuntime(19935):    at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
E/AndroidRuntime(19935):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19935):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19935):    at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(19935):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19935):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19935):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(19935):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(19935):    at dalvik.system.NativeStart.main(Native Method)

**Comment by theJenix** [comment]
Duplicate of #165
