### ISSUE TITLE
Bluetooth may sometimes fail without warning when connecting.

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#216]
This usually requires the user to manually disable and enable bluetooth, or restart the phone.  It has been observed on both Nexus 4 and Samsung Galaxy S3 devices.  The goal of this ticket is to investigate the issue, provide a warning to the user to say "You probably need to restart bluetooth", and attempt to restart services automatically if we find it helps.

---

Logcat capture, new network, connecting one guest:

W/BluetoothDiscoveryHandler(24210): Discovery finished
V/BluetoothDiscoveryReceiver(24637): Received: android.bluetooth.adapter.action.DISCOVERY_FINISHED
D/overlay (  159): Unset pipe=VG0 dpy=0; Unset pipe=RGB1 dpy=0;
I/dalvikvm(24210): Jit: resizing JitTable from 4096 to 8192
I/GAV2    (24210): Thread[GAThread,5,main]: putHit called
I/GAV2    (24210): Thread[GAThread,5,main]: Sending hit to store
W/BluetoothAdapter(24210): getBluetoothService() called with no BluetoothManagerCallback
D/BTIF_SOCK( 1149): service_uuid: e271f460-d1ad-4ea8-b555-5e59b19c71ff
D/BluetoothSocket(24210): connect(), SocketState: INIT, mPfd: {ParcelFileDescriptor: FileDescriptor[52]}
W/InputMethodManagerService(  532): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@43295020 attribute=null, token = android.os.BinderProxy@426bc6f0
D/overlay (  159): Set pipe=RGB1 dpy=0; Set pipe=VG0 dpy=0;
W/bt-btif ( 1149): info:x10
W/bt-sdp  ( 1149): process_service_search_attr_rsp
W/bt-rfcomm( 1149): RFCOMM_CreateConnection - no resources
E/bt-btif ( 1149): bta_jv_rfcomm_connect, RFCOMM_CreateConnection failed
W/bt-btif ( 1149): invalid rfc slot id: 2567
E/ConnectThread(24210): Unable to connect socket
E/ConnectThread(24210): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
E/ConnectThread(24210):     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:492)
E/ConnectThread(24210):     at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:469)
E/ConnectThread(24210):     at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:322)
E/ConnectThread(24210):     at com.lastcrusade.soundstream.net.ConnectThread.doInBackground(ConnectThread.java:66)
E/ConnectThread(24210):     at com.lastcrusade.soundstream.net.ConnectThread.doInBackground(ConnectThread.java:41)
E/ConnectThread(24210):     at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/ConnectThread(24210):     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/ConnectThread(24210):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/ConnectThread(24210):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/ConnectThread(24210):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/ConnectThread(24210):     at java.lang.Thread.run(Thread.java:856)
D/overlay (  159): Unset pipe=VG0 dpy=0; Unset pipe=RGB1 dpy=0;
D/BluetoothManagerService(  532): checkIfCallerIsForegroundUser: valid=true callingUser=0 foregroundUser=0
W/BluetoothAdapter(20150): getBluetoothService() called with no BluetoothManagerCallback
E/BluetoothServiceJni( 1149): SOCK FLAG = 3 ***********************
W/bt-rfcomm( 1149): RFCOMM_CreateConnection - no resources
E/bt-btif ( 1149): bta_jv_rfcomm_start_server, RFCOMM_CreateConnection failed
W/bt-btif ( 1149): invalid rfc slot id: 2568
E/BluetoothSocket(20150): bindListen, fail to get port number, exception: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
E/bt-btm  ( 1149): btm_sec_disconnected - Clearing Pending flag
D/overlay (  159): Set pipe=RGB1 dpy=0; Set pipe=VG0 dpy=0;
D/dalvikvm(23360): GC_CONCURRENT freed 500K, 6% free 9637K/10192K, paused 2ms+2ms, total 30ms

Logcat capture, Connecting 2nd guest, 1st guest disconnected unexpectedly

/BluetoothDiscoveryHandler(25003): Device found: Nexus 4(98:D6:F7:DB:75:7C)
D/BluetoothAdapterService(1113739064)( 1149): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@42625398
D/BluetoothAdapterService(1113739064)( 1149): Get Bonded Devices being called
D/BluetoothEventManager(24637): DeviceFoundHandler created new CachedBluetoothDevice: 98:D6:F7:DB:75:7C
W/BluetoothDiscoveryHandler(25003): Device found: XXX
D/BluetoothAdapterService(1113739064)( 1149): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@42625398
D/BluetoothAdapterService(1113739064)( 1149): Get Bonded Devices being called
D/BluetoothEventManager(24637): DeviceFoundHandler created new CachedBluetoothDevice: E4:CE:8F:0C:24:1F
W/BluetoothDiscoveryHandler(25003): Device found: XXX
D/BluetoothAdapterService(1113739064)( 1149): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@42625398
D/BluetoothAdapterService(1113739064)( 1149): Get Bonded Devices being called
D/BluetoothEventManager(24637): DeviceFoundHandler created new CachedBluetoothDevice: 58:B0:35:69:D0:95
E/bt-btm  ( 1149): btm_sec_disconnected - Clearing Pending flag
W/bt-btif ( 1149): invalid rfc slot id: 2573
W/System.err(25003): java.io.IOException: bt socket closed, read return: -1
W/System.err(25003):    at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:416)
W/System.err(25003):    at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
W/System.err(25003):    at com.lastcrusade.soundstream.net.wire.Messenger.blockAndReadOne(Messenger.java:227)
W/System.err(25003):    at com.lastcrusade.soundstream.net.wire.Messenger.readNext(Messenger.java:249)
W/System.err(25003):    at com.lastcrusade.soundstream.net.wire.Messenger.deserializeMessage(Messenger.java:154)
W/System.err(25003):    at com.lastcrusade.soundstream.net.MessageThread.run(MessageThread.java:135)
W/BluetoothDiscoveryHandler(25003): Device found: XXX

**Comment by theJenix** [comment]
We may be able to incorporate the dialog added in pull request #308 to build in a possible workaround for this issue.  In my testing, cycling bluetooth on and off seems to fix this problem.
